name: smart_factory_app
description: Smart Factory Education App
publish_to: 'none'
version: 1.0.9+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.4.2
  youtube_player_iframe: ^4.0.4
  url_launcher: ^6.2.5
  timezone: ^0.9.2
  flutter_svg: ^2.0.9
  video_player: ^2.8.2
  chewie: ^1.7.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  # dart_snap7: ^0.5.3  # Replaced with Moka7 via MethodChannel

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/Industrial Maintenance - IM0004 Maintenance of closed loop systems Overview.mp4

